#!/usr/bin/env python3
"""Regenerate docs/PLC_TAGS.md and plc/st/tags_generated.st from qd_plc.tags.

Run this after changing any tag. The OpenPLC slave-device config gets typed
into a web form by hand, and the ST VAR block gets compiled - if either drifts
from what the sim actually publishes, the symptom is an operator panel full of
plausible wrong numbers and no error anywhere. Generating both from the same
source is the only reliable defence.

    venv/bin/python scripts/gen_plc_docs.py [--check]

--check exits non-zero if the generated files are out of date, for CI.
"""

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from qd_plc.tags import (MAP_A, MAP_B, CellState, DType, Fault, Kind, Phase,
                         FAULT_TEXT, PHASE_TEXT,
                         openplc_address, openplc_slave_config, st_var_block)

DOC = ROOT / "docs" / "PLC_TAGS.md"
ST = ROOT / "plc" / "st" / "tags_generated.st"

KIND_TITLE = {
    Kind.DISCRETE_INPUT: ("Discrete Inputs", "sim reads nothing here; PLC polls these as status"),
    Kind.COIL: ("Coils", "commands"),
    Kind.INPUT_REG: ("Input Registers", "measured values, read-only to the master"),
    Kind.HOLDING_REG: ("Holding Registers", "setpoints"),
}


def _scale_text(tag):
    if tag.dtype == DType.BOOL:
        return ""
    if tag.dtype == DType.ENUM:
        return f"enum {tag.enum}"
    if tag.scale == 1.0:
        return tag.unit or "count"
    return f"{tag.scale:g} {tag.unit}".strip()


def _table(tmap, kind, master):
    tags = tmap.of_kind(kind)
    if not tags:
        return []
    title, gloss = KIND_TITLE[kind]
    out = [f"### {title} ({gloss})", "",
           "| Addr | IEC | Name | Type | Scale | Sticky | Description |",
           "|---:|---|---|---|---|:-:|---|"]
    for t in tags:
        out.append(
            f"| {t.addr} | `{openplc_address(t, master=master)}` | `{t.name}` | "
            f"{t.dtype} | {_scale_text(t)} | {'yes' if t.sticky else ''} | "
            f"{t.desc} |"
        )
    spare = tmap.spare(kind)
    if spare:
        rng = f"{spare[0]}-{spare[-1]}" if len(spare) > 1 else str(spare[0])
        out += ["", f"Spare: {rng} (declared block size "
                    f"{tmap.size(kind)}; reserved so a later addition "
                    f"does not shift the addresses above)."]
    out.append("")
    return out


def _enum_table(name, enum, text=None):
    out = [f"### {name}", "", "| Value | Name | Operator text |", "|---:|---|---|"]
    for m in enum:
        out.append(f"| {m.value} | `{m.name}` | {text.get(m, '') if text else ''} |")
    out.append("")
    return out


def build_doc():
    L = [
        "# PLC tag reference",
        "",
        "**Generated by `scripts/gen_plc_docs.py` from `qd_plc/tags.py` - do "
        "not edit by hand.**",
        "",
        "Two Modbus links, two different maps. Map A is the machine "
        "interface between the robot controller and the cell PLC; Map B is "
        "the supervisory view between the PLC and the operator panel. They "
        "are deliberately not the same set of signals.",
        "",
        "Scaling: Modbus carries 16-bit words only, so every physical value "
        "is an integer with an agreed scale (`8.42 mm` travels as `842`). "
        "`qd_plc/datastore.py` applies each tag's scale on the way in and "
        "out.",
        "",
        "---",
        "",
        "## OpenPLC slave-device configuration",
        "",
        "Type these into **Slave Devices -> Add** in the OpenPLC web UI, for "
        "a Generic Modbus TCP device on port 5020. Use the Mac's **IPv4 "
        "address** as seen from the container, not `host.docker.internal` - "
        "OpenPLC's Modbus master cannot resolve hostnames. "
        "`scripts/plc_configure.py` looks it up for you. "
        "**Order and size matter**: OpenPLC derives every `%`-address from "
        "them, so resizing a block silently shifts everything after it.",
        "",
        "| Field | Start | Size | Resulting `%` range |",
        "|---|---:|---:|---|",
    ]
    for label, start, size, span in openplc_slave_config():
        L.append(f"| {label} | {start} | {size} | {span} |")
    L += [
        "",
        "Holding Registers - Read is sized **0** on purpose: everything the "
        "PLC reads from the sim is already an input register, and a second "
        "copy would be a second source of truth for the same words.",
        "",
        "---",
        "",
        f"## Map A - {MAP_A.description}",
        "",
        "Sim listens on `0.0.0.0:5020`, unit 1. Binding loopback instead is "
        "the most common reason OpenPLC reports the slave offline.",
        "",
        "Bits marked **sticky** are latched set-only by the sim and cleared "
        "only by the `CLEAR_STICKY` coil. The sim free-runs far faster than "
        "OpenPLC polls, so an unlatched transient could be raised and "
        "cleared entirely between two polls and never be seen.",
        "",
    ]
    for kind in (Kind.DISCRETE_INPUT, Kind.COIL, Kind.INPUT_REG, Kind.HOLDING_REG):
        L += _table(MAP_A, kind, master=True)
    L += [
        "---",
        "",
        f"## Map B - {MAP_B.description}",
        "",
        "An IEC 61131 program cannot write `%IX` or `%IW`, and in OpenPLC "
        "that space is taken by the master mapping. So PLC-to-HMI status "
        "lives in coils and holding registers with an ownership split by "
        "address range rather than by object type:",
        "",
        "| Range | Written by | Read by |",
        "|---|---|---|",
        "| coils 0-15 | PLC | HMI |",
        "| coils 80-95 | HMI | PLC |",
        "| registers 0-35 | PLC | HMI |",
        "",
        "Anything at `%QX100.0`/`%QW100` or above belongs to the sim link "
        "and is out of bounds for the HMI.",
        "",
    ]
    for kind in (Kind.COIL, Kind.HOLDING_REG):
        L += _table(MAP_B, kind, master=False)
    L += ["---", "", "## Enumerations", ""]
    L += _enum_table("Phase (PHASE_CODE, CURRENT_STEP)", Phase, PHASE_TEXT)
    L += ["Phase codes are decade-aligned, so a code reads as its stage at a "
          "glance: 10s the tray, 20s the pick, and so on.", ""]
    L += _enum_table("CellState (Map B CELL_STATE)", CellState)
    L += _enum_table("Fault (ACTIVE_FAULT_CODE)", Fault, FAULT_TEXT)
    return "\n".join(L) + "\n"


def build_st():
    return (
        "(* Generated by scripts/gen_plc_docs.py from qd_plc/tags.py.\n"
        "   Do not edit by hand - regenerate instead.\n"
        "   Addresses are derived from the OpenPLC slave-device sizes in\n"
        "   docs/PLC_TAGS.md; if you retype that config differently, these\n"
        "   stop matching the registers the sim publishes. *)\n\n"
        + st_var_block() + "\n"
    )


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if the generated files are stale")
    args = ap.parse_args()

    wanted = {DOC: build_doc(), ST: build_st()}
    stale = [p for p, text in wanted.items()
             if not p.exists() or p.read_text() != text]

    if args.check:
        for p in stale:
            print(f"STALE: {p.relative_to(ROOT)}")
        if stale:
            print("\nRun: venv/bin/python scripts/gen_plc_docs.py")
            return 1
        print("generated files are up to date")
        return 0

    for p, text in wanted.items():
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(text)
        print(f"wrote {p.relative_to(ROOT)} ({len(text.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
